openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Contacts Book>
tags:
  - name: Contacts
    description: Operations about users.
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-l6rc.onrender.com
  #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
